spring:
  application:
    name: wom-auth-service-api
  
  profiles:
    active: dev

  # Configuración de Base de Datos
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:wom_auth_db}
    username: ${POSTGRES_USER:wom_user}
    password: ${POSTGRES_PASSWORD:wom_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Flyway - Migraciones
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

  # Redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms

  # Jackson
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Configuración de Seguridad JWT
jwt:
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}      # 15 minutos (en milisegundos)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 días (en milisegundos)
  private-key-path: ${JWT_PRIVATE_KEY_PATH:classpath:keys/private_key.pem}
  public-key-path: ${JWT_PUBLIC_KEY_PATH:classpath:keys/public_key.pem}

# Configuración de Seguridad
security:
  max-login-attempts: ${MAX_LOGIN_ATTEMPTS:5}
  account-lock-duration-minutes: ${ACCOUNT_LOCK_DURATION:30}
  password-min-length: 8
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

# Rate Limiting
rate-limit:
  login:
    capacity: 5
    refill-tokens: 5
    refill-duration-minutes: 1
  refresh:
    capacity: 10
    refill-tokens: 10
    refill-duration-minutes: 1
  logout:
    capacity: 10
    refill-tokens: 10
    refill-duration-minutes: 1

# Spring Boot Actuator - Monitoreo
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  health:
    redis:
      enabled: true
    db:
      enabled: true

# Logging
logging:
  level:
    root: INFO
    com.wom.auth: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI / Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true

# Server
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
