spring:
  config:
    activate:
      on-profile: prod

  # Base de datos en producción (fly.io)
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Redis en producción (fly.io)
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    ssl: true

  # JPA - Sin logs en producción
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Logging mínimo en producción
logging:
  level:
    root: WARN
    com.wom.auth: INFO
    org.springframework.security: WARN
    org.hibernate: WARN

# Actuator - Solo lo necesario
management:
  endpoint:
    health:
      show-details: always
