spring:
  config:
    activate:
      on-profile: dev

  # Base de datos local con Docker
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:wom_auth_db}
    username: ${POSTGRES_USER:wom_user}
    password: ${POSTGRES_PASSWORD:wom_password}

  # Redis local con Docker
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ""

  # JPA - Mostrar SQL en desarrollo
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT - Tiempos más cortos para testing
jwt:
  expiration:
    access-token: 900000    # 15 minutos
    refresh-token: 604800000 # 7 días

# Logging detallado en desarrollo
logging:
  level:
    root: INFO
    com.wom.auth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator - Mostrar todos los detalles
management:
  endpoint:
    health:
      show-details: always
