spring:
  config:
    activate:
      on-profile: prod

  # JPA - Sin logs en producción
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Logging mínimo en producción
logging:
  level:
    root: WARN
    com.wom.auth: INFO
    org.springframework.security: WARN
    org.hibernate: WARN

# Actuator - Solo lo necesario
management:
  endpoint:
    health:
      show-details: when-authorized
